http:
  port: "8091"
  
anypoint:
  api:
    id: "1"
  app:
    clientId: "xxxxx"
    clientSecret: "yyyyy"
  businessGroup: "3ab0f923-8bcb-4e7b-aa6e-0b984a18c811"
  portal:
    assetId: anypoint-race-api
    version: "2.0.0"
    timeout: "20000"
    pages:
      results:
        firstToFinish: "7aq-sjs/Results: First to Finish"
        fastest: "0t1-29r/Results: Fastest"
        most: "99i-oc0/Results: Perseverance"
        halloffame: "5ip-grn/Hall of Fame"
        easterEgg: "dla-n7g/Results: Easter Egg"
        
referee:
  host: localhost
  port: "8092"
  protocol: HTTP
  path: /api
  
racedata:
  host: localhost
  port: "8093"
  protocol: HTTP
  path: /api

race:
  expiry: "600" # seconds

practice:
  expiry: "600" # seconds